#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source experimental_helper.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE FROM ADMIN PANEL
#=================================================

# Remove a service from the admin panel, added by `yunohost service add`
yunohost service remove $app
yunohost service remove $app-coturn

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service" --weight=2

ynh_remove_systemd_config --service=$app
ynh_remove_systemd_config --service=$app-coturn

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing app main directory" --weight=2

ynh_secure_remove --file=$code_dir
ynh_secure_remove --file=/etc/matrix-$app
ynh_secure_remove --file=/etc/nginx/conf.d/${server_name}.d/${app}_server_name.conf

if [ "$YNH_APP_PURGE" -eq 1 ]; then
    ynh_script_progression --message="Removing logs..."
    ynh_secure_remove --file=/var/log/matrix-"$app"
fi

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration" --weight=2

# Remove the dedicated nginx config
ynh_remove_nginx_config

# Remove the dedicated php-fpm config
ynh_remove_fpm_config

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration" --weight=1

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# REMOVE FAIL2BAN CONFIGURATION
#=================================================
ynh_script_progression --message="Removing Fail2Ban configuration..." --weight=8

# Remove the dedicated fail2ban config
ynh_remove_fail2ban_config

#=================================================
# GENERIC FINALIZATION
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
sleep 1
